# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '30 1 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml pandas selenium webdriver_manager
      - name: Run script
        run: python pychart_M_concert10.py
        working-directory: ./path/to/your/script
      - name: Commit results
        run: |
          git config --global user.email "hyeji1364@gmail.com"
          git config --global user.name "Hyeji1364"
          git add melonconcert/chart_M_concert10_*.json
          git commit -m "차트 수집 완료"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
